"""
Advanced report drafting & data visualisation (improvements #22, #19).

``ReportDrafter`` turns a brief into a structured, well-written report using the
provider router (cloud when online, local Ollama when offline), and renders any
supplied figures as clean **inline SVG charts generated in pure Python** — so
data visualisation needs no matplotlib and works entirely offline.

Output is always a self-contained document written into an organised, dated
folder under ``reports/``:
    • ``report.md``   — always (Markdown, universally readable);
    • ``report.html`` — always (Markdown + embedded SVG charts, opens anywhere);
    • ``report.docx`` — additionally, when ``python-docx`` is installed.

Chart data is passed as ``{"title": str, "data": {label: value, …}}`` items;
each becomes a labelled bar chart.  The narrative is generated by the router
with a report-writer persona and grounded strictly in the brief.
"""

from __future__ import annotations

import asyncio
import html
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from .bus import OrionBus
from .constants import BASE_DIR, C
from .data import ToolResult
from .security import SecuritySanitiser, SecurityViolation
from .utils import first_line, utc_stamp

REPORTS_DIR = BASE_DIR / "reports"


class ReportDrafter:
    def __init__(self, bus: OrionBus, router: Any, telemetry: Any | None = None) -> None:
        self.bus = bus
        self.router = router
        self.telemetry = telemetry
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    async def draft(self, topic: str, brief: str = "",
                    charts: Optional[list[dict[str, Any]]] = None,
                    sections: Optional[list[str]] = None) -> ToolResult:
        try:
            topic = SecuritySanitiser.guard_text(str(topic or "").strip(), "report.topic")
        except SecurityViolation as exc:
            return ToolResult(str(exc), ok=False)
        if not topic:
            return ToolResult("What should the report be about, sir?", ok=False)
        sections = sections or ["Executive Summary", "Analysis", "Findings", "Recommendations"]
        narrative = await self._write(topic, brief, sections)
        chart_svgs = [self._bar_chart(c) for c in (charts or []) if isinstance(c, dict)]
        folder = REPORTS_DIR / f"{datetime.now():%Y-%m-%d}_{self._slug(topic)}"
        folder.mkdir(parents=True, exist_ok=True)
        written = await asyncio.to_thread(self._write_files, folder, topic, narrative, chart_svgs)
        if self.telemetry is not None:
            self.telemetry.metrics.incr("report.drafted")
        return ToolResult(
            f"Report drafted, sir: '{topic}'. Wrote {', '.join(written)} to "
            f"{folder.relative_to(BASE_DIR)}."
        )

    # ── narrative ─────────────────────────────────────────────────────────────

    async def _write(self, topic: str, brief: str, sections: list[str]) -> str:
        if not self.router.has_text_fallback():
            body = [f"# {topic}", f"_Drafted {utc_stamp()}_", ""]
            for s in sections:
                body.append(f"## {s}\n\n_(No language model reachable; provide notes to expand.)_\n")
            if brief:
                body.append(f"## Brief\n\n{brief}\n")
            return "\n".join(body)
        persona = (
            "You are ORION drafting a professional report for the user. Write in clear, "
            "confident British English. Use the exact section headings provided as '## '. "
            "Be specific and structured; do not invent data not present in the brief."
        )
        prompt = (
            f"Draft a report titled '{topic}'.\n"
            f"Sections (use each as a '## ' heading): {', '.join(sections)}.\n"
            + (f"Brief / source notes:\n{brief}\n" if brief.strip() else "")
            + "Return Markdown starting with '# " + topic + "'."
        )
        try:
            _profile, text = await self.router.generate_text(prompt, system_extra=persona)
            return text if text.strip().startswith("#") else f"# {topic}\n\n{text}"
        except Exception as exc:
            return f"# {topic}\n\n_(Report model unavailable: {first_line(exc, 80)})_\n\n{brief}"

    # ── pure-Python SVG bar chart ─────────────────────────────────────────────

    def _bar_chart(self, chart: dict[str, Any]) -> str:
        title = str(chart.get("title") or "Chart")
        data = chart.get("data") or {}
        pairs = [(str(k), float(v)) for k, v in data.items()
                 if isinstance(v, (int, float))] if isinstance(data, dict) else []
        if not pairs:
            return ""
        width, bar_h, gap, left = 520, 26, 12, 130
        height = 40 + len(pairs) * (bar_h + gap)
        peak = max(v for _, v in pairs) or 1.0
        parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
            f'viewBox="0 0 {width} {height}" role="img">',
            f'<rect width="{width}" height="{height}" fill="{C.BG}"/>',
            f'<text x="12" y="24" fill="{C.PRI}" font-family="Segoe UI,Arial" '
            f'font-size="14" font-weight="700">{html.escape(title)}</text>',
        ]
        y = 40
        for label, value in pairs:
            bar_w = (value / peak) * (width - left - 60)
            parts.append(
                f'<rect x="{left}" y="{y}" width="{max(1, bar_w):.1f}" height="{bar_h}" '
                f'rx="4" fill="{C.PRI}"/>'
            )
            parts.append(
                f'<text x="{left - 8}" y="{y + bar_h - 8}" text-anchor="end" '
                f'fill="{C.WHITE}" font-family="Segoe UI,Arial" font-size="12">'
                f'{html.escape(label[:20])}</text>'
            )
            parts.append(
                f'<text x="{left + bar_w + 6:.1f}" y="{y + bar_h - 8}" fill="{C.MUTED}" '
                f'font-family="Segoe UI,Arial" font-size="11">{value:,.0f}</text>'
            )
            y += bar_h + gap
        parts.append("</svg>")
        return "".join(parts)

    # ── file writing ──────────────────────────────────────────────────────────

    def _write_files(self, folder: Path, topic: str, narrative: str,
                     charts: list[str]) -> list[str]:
        written: list[str] = []
        (folder / "report.md").write_text(
            narrative + ("\n\n## Figures\n\n" + "\n\n".join(
                f"![chart {i}](chart_{i}.svg)" for i, _ in enumerate(charts, 1)) if charts else ""),
            encoding="utf-8",
        )
        written.append("report.md")
        for i, svg in enumerate(charts, 1):
            (folder / f"chart_{i}.svg").write_text(svg, encoding="utf-8")
        # Self-contained HTML with embedded SVG.
        html_body = self._markdown_to_html(narrative)
        charts_html = "".join(f'<div class="chart">{svg}</div>' for svg in charts if svg)
        (folder / "report.html").write_text(self._html_document(topic, html_body, charts_html),
                                            encoding="utf-8")
        written.append("report.html")
        # Optional DOCX if python-docx is present.
        if self._write_docx(folder, topic, narrative):
            written.append("report.docx")
        return written

    def _write_docx(self, folder: Path, topic: str, narrative: str) -> bool:
        try:
            import docx  # type: ignore
        except Exception:
            return False
        try:
            document = docx.Document()
            for line in narrative.splitlines():
                if line.startswith("# "):
                    document.add_heading(line[2:], level=0)
                elif line.startswith("## "):
                    document.add_heading(line[3:], level=1)
                elif line.startswith("### "):
                    document.add_heading(line[4:], level=2)
                elif line.strip():
                    document.add_paragraph(line)
            document.save(str(folder / "report.docx"))
            return True
        except Exception:
            return False

    @staticmethod
    def _slug(text: str) -> str:
        return re.sub(r"[^a-z0-9]+", "-", str(text or "").lower()).strip("-")[:48] or "report"

    @staticmethod
    def _markdown_to_html(md: str) -> str:
        out: list[str] = []
        for line in md.splitlines():
            if line.startswith("### "):
                out.append(f"<h3>{html.escape(line[4:])}</h3>")
            elif line.startswith("## "):
                out.append(f"<h2>{html.escape(line[3:])}</h2>")
            elif line.startswith("# "):
                out.append(f"<h1>{html.escape(line[2:])}</h1>")
            elif line.strip().startswith(("- ", "* ")):
                out.append(f"<li>{html.escape(line.strip()[2:])}</li>")
            elif line.strip():
                out.append(f"<p>{html.escape(line)}</p>")
        return "\n".join(out)

    @staticmethod
    def _html_document(topic: str, body: str, charts: str) -> str:
        return (
            f"<!doctype html><html><head><meta charset='utf-8'><title>{html.escape(topic)}</title>"
            f"<style>body{{background:{C.BG};color:{C.WHITE};font-family:'Segoe UI',Arial;"
            f"max-width:820px;margin:32px auto;padding:0 20px;line-height:1.55}}"
            f"h1,h2,h3{{color:{C.PRI}}} .chart{{margin:18px 0}} li{{margin:2px 0}}</style></head>"
            f"<body>{body}{('<h2>Figures</h2>' + charts) if charts else ''}</body></html>"
        )
